### ISSUE TITLE
Diurnal cycles

### ISSUE THREAD

**Issue by vergauwenthomas** [vergauwenthomas/MetObs_toolkit#102]
1. Make a function that creates a diurnal cycle for a collection of observations. Do this by aggregating to the hour and minutes.
These are extra arguments:

- stations: can be a list of stations, or one station, to subset the observations to. If not given, use all available stations
- absolute/relative: choose if a users wants the absolute averages, or averages of differences wrt a reference stations. The user should define a reference stations, if not by default use the first stations. 

The function returns a dataframe with as index the aggregated timestamps, columns are the stationnames and the values the aggregated diurnal values for that station. 

2 Make a plotting function for this.

**Comment by ACovaci99** [comment]
I have written the diurnal cycle function, I hope that the format of the final data frame is what you were thinking of.
