### ISSUE TITLE
get station gaps 

### ISSUE THREAD

**Issue by vergauwenthomas** [vergauwenthomas/MetObs_toolkit#175]
bug when extract station gaps when station has one gap.

**Comment by vergauwenthomas** [comment]
example: the gaps is in the stations (with one gap), but it is not plotted:
![Screenshot from 2023-05-16 17-48-50](https://github.com/vergauwenthomas/MetObs_toolkit/assets/82087298/68ce74b8-a2ff-4988-af19-cb1b9af7143f)

**Comment by ACovaci99** [comment]
I tried many things but could not get the same plot, no matter what I did. 
I only get ones like this
![image](https://github.com/vergauwenthomas/MetObs_toolkit/assets/118910836/19d00bd9-5b1d-45c9-aad7-817972f4a9b0)
or like this 
![image](https://github.com/vergauwenthomas/MetObs_toolkit/assets/118910836/643582f0-b221-49e5-a557-257ebd4889c0)
Perhaps, I am working with the wrong data set for this one, but for testdata_okt_small.csv and testdata_okt.csv, there are no gaps for station vlinder05.

**Comment by vergauwenthomas** [comment]
@ACovaci99 
There is initially indeed no gap for vlinder05, but there is a long period of repetitions outliers. So if you than apply [update_gaps_and_missing_from_outliers](https://vergauwenthomas.github.io/MetObs_toolkit/_autosummary/metobs_toolkit.dataset.Dataset.html#metobs_toolkit.dataset.Dataset.update_gaps_and_missing_from_outliers) , than this period is interpreted as a gap. I will take a look in to it myself

**Comment by vergauwenthomas** [comment]
@amberJ99 
Ik denk dat het probleem is opgelost, al weet ik niet wanneer dat is gebeurt. 

Hier een overzichtje van vlinder05 voor oktober, wat een 'specialeke' is:


![Screenshot from 2023-05-26 12-20-15](https://github.com/vergauwenthomas/MetObs_toolkit/assets/82087298/9c9d1cb7-8f68-48b3-bfde-d29f4d33eba5)

Er zijn twee lange periodes van repetitions, en vele kleine. Enkel de twee lange periodes worden door gezien als gaps. Deze heb ik proberen opvullen met interpolatie, maar er is geen leading voor de eerste gap, en geen trailing voor de tweede, dus is gapfill niet mogelijk. 

Alles wordt dus correct voorgesteld.
