### ISSUE TITLE
Unclear instructions in Examples page in the documentation

### ISSUE THREAD

**Issue by ashwinvis** [vergauwenthomas/MetObs_toolkit#384]
I would like to get started, but I don't see where I should obtain the data from. Also the code snippet is truncated in the beginning. So some variables are undefined.

https://vergauwenthomas.github.io/MetObs_toolkit/examples.html

cf: https://github.com/openjournals/joss-reviews/issues/5916

**Comment by Zeitsperre** [comment]
Nicely done!
