### ISSUE TITLE
[JOSS] Paper Commentary

### ISSUE THREAD

**Issue by Zeitsperre** [vergauwenthomas/MetObs_toolkit#387]
Context: https://github.com/openjournals/joss-reviews/issues/5916

This is a list of some recommendations that could help with the paper submission:
- [x] The Statement of Need could benefit from some/most of the information found in the first paragraph of the summary. Do the software outputs adhere to/enforce existing standards for weather station data (WMO guidelines, ISOs, CF-Conventions)? Expand on the frameworks/standards/approaches you are building upon?
- [x] "Quality control is performed in the form of a series of checks" - Elaborate? What are you checking for exactly at the time of writing (monotonic timestamps, data gaps, extremes, etc.)?
- [x] "It is to be expected that some novel functionalities will be added in the coming years and the documentation will be updated accordingly." - Unless the features are already planned for and can be described, I'd remove this line. The paper should showcase that the software is feature-complete (even if there are new features being planned; the paper doesn't prevent you from expanding the software in future versions). This statement can be easily rolled into the first line of the preceding paragraph if needed.
- [x] The citation for the Pandas team needs to be fixed: `"team, T. pandas development"`

There are a handful of phrases that could be tightened as well (if the authors like, I can suggest a few changes in a PR). I might also have some small additional comments after more reflection.

**Comment by vergauwenthomas** [comment]
Other comments:

- [ ] Reproducibility: I believe the results shown in Figure 1 is based on the Examples section in the docs. The author should point out that.
- [ ] References: Fix Caluwaerts et al. title The urban climate of ghent, belgium... and the citation for Pandas.

**Comment by Zeitsperre** [comment]
@vergauwenthomas The latest draft of the paper addresses many of the issues I raised (and flows much better). There are a handful of small grammatical errors that I can fix if you'd like (let me know), but I consider this issue addressed!

**Comment by vergauwenthomas** [comment]
@Zeitsperre thanks!  If you could pinpoint the grammatical errors that would be great, but only if you have time for it. (If you do, and prefer to fix the errors in the paper.md you are free to do so.)

btw #400 is merged to master.
