### ISSUE TITLE
[JOSS] Paper minor corrections 

### ISSUE THREAD

**Issue by vergauwenthomas** [vergauwenthomas/MetObs_toolkit#452]
Minor corrections suggestions by @ashwinvis:

“48 ... data for analysis by making intensive use of the pandas (The pandas development team, 2023) and geopandas (Jordahl et al., 2020) functionalities” (Vergauwen et al., 2024, p. 2) (pdf)

*use of the functionalities from pandas (..) and geopandas (..) libraries.

“52 data is imported into the Toolkit Dataset” (Vergauwen et al., 2024, p. 3) (pdf)

into a Toolkit Dataset class instance

“61 Modeldata” (Vergauwen et al., 2024, p. 3) (pdf)

Modeldata class instance

Finally could you make the typography consistent between

Toolkit Dataset
Toolkit Modeldata
Toolkit-Analysis
?

**Comment by vergauwenthomas** [comment]
Ref: https://github.com/openjournals/joss-reviews/issues/5916

**Comment by amberJ99** [comment]
Can you add my FWO number to the publication?
My number is 11PBN24N.

**Comment by vergauwenthomas** [comment]
Refer to the documentation (version) for more details:

Further reading and citations needed here
Since MetObs-Toolkit implements quite a few methods, it would be important to link to other sources which may describe them in detail. If you think that these methods might be subject to change, it might be sufficient to cite the references in the online documentation and link this software paper to the documentation instead. See how [scikit-image](https://scikit-image.org/docs/stable/api/skimage.filters.html#skimage.filters.butterworth) does it.

“55 to examine data types, irregular timestamps, max-min thresholds, repetitions criteria, spike tests, allowed variation in time windows and spatial tests” (Vergauwen et al., 2024, p. 3) (pdf)

These, IMHO, are quite involved methods. What are the formal basis behind these QC methods or are they based on intuition? Some reuses TITAN (titanlib) while the rest are implemented from the scratch (which means citing TITAN alone will not be sufficient). .

“59 ... gap filling is applied by using interpolation methods” (Vergauwen et al., 2024, p. 3) (pdf)

Gap filling and bias correction is another involved topic. What is the basis behind the methods used? Further reading and citations needed here.

**Comment by vergauwenthomas** [comment]
> Finally could you make the typography consistent between
> 
> Toolkit Dataset Toolkit Modeldata Toolkit-Analysis ?

When referring to a class of the toolkit i used recursive.
