### ISSUE TITLE
Remove duplicates in invalid_input_check

### ISSUE THREAD

**Issue by MichielVieijra** [vergauwenthomas/MetObs_toolkit#90]
Remove appearance of duplicate outliers in invalid input check

**Comment by vergauwenthomas** [comment]
@MichielVieijra I also found this faulty behaviour:
![Screenshot from 2023-03-21 15-29-36](https://user-images.githubusercontent.com/82087298/226638935-de06163b-3c64-4f74-a2aa-02b5d6718d85.png)

As you can see, in the outlierdf there is a stacking of invalid outliers for the same timestamp but for different observation types. This should be present as one row.
